import React, { useState } from 'react';
import {
  Share2,
  Copy,
  CheckCircle2,
  DollarSign,
  Users,
  Award,
  ArrowUpRight,
  QrCode,
  ShieldCheck,
  Zap,
} from 'lucide-react';
import { useApp } from '../../context/AppContext';

export const ReferralView: React.FC = () => {
  const { user, addToast } = useApp();
  const [copied, setCopied] = useState(false);
  const [isPayoutModalOpen, setIsPayoutModalOpen] = useState(false);
  const [payoutMethod, setPayoutMethod] = useState<'USDT' | 'BANK'>('USDT');
  const [walletAddress, setWalletAddress] = useState('TX9eRtK89Z14q8L0a...');

  const referralLink = `https://botxchange.io/ref/${user?.referralCode || 'ALPHA77'}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(referralLink);
    setCopied(true);
    addToast({
      title: 'Referral Link Copied',
      message: 'Share your link to earn up to 30% lifetime automated broker commissions.',
      type: 'success',
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePayout = () => {
    setIsPayoutModalOpen(false);
    addToast({
      title: 'Payout Request Dispatched',
      message: 'Withdrawal of $480.00 submitted for batch settlement.',
      type: 'success',
    });
  };

  return (
    <div className="space-y-8 pb-16">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 rounded-2xl bg-[#0e1420] border border-slate-800 shadow-xl">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight">
              Affiliate &amp; Partner Network
            </h1>
            <span className="px-2 py-0.5 rounded-full bg-amber-500/20 text-amber-400 font-bold text-[10px]">
              TIER 3: GOLD (25%)
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Earn perpetual revenue share from all trading volume and subscription fees generated by your network.
          </p>
        </div>

        <button
          onClick={() => setIsPayoutModalOpen(true)}
          className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 text-slate-950 font-bold text-xs transition shadow-lg shadow-amber-500/20 cursor-pointer flex items-center gap-2 self-start sm:self-auto"
        >
          <DollarSign className="w-4 h-4" />
          <span>Request Payout ($480.00)</span>
        </button>
      </div>

      {/* Referral Link & Share Box */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-slate-900 via-[#0e1420] to-slate-900 border border-slate-800 shadow-xl space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-1">
            <h3 className="text-base font-bold text-white">Your Global Partner Link</h3>
            <p className="text-xs text-slate-400">
              Users who register via this URL receive a $100 broker rebate voucher.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <div className="px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-700 font-mono text-xs text-amber-400 select-all">
              {referralLink}
            </div>
            <button
              onClick={handleCopy}
              className="px-4 py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold text-xs transition shadow-lg flex items-center gap-1.5 cursor-pointer"
            >
              {copied ? <CheckCircle2 className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied!' : 'Copy Link'}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Referral Metric Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="p-4 rounded-2xl bg-[#0e1420] border border-slate-800">
          <div className="text-xs text-slate-400">Total Referrals</div>
          <div className="text-2xl font-black font-mono text-white mt-1">28 Traders</div>
          <div className="text-[10px] text-emerald-400 mt-0.5">+4 this month</div>
        </div>

        <div className="p-4 rounded-2xl bg-[#0e1420] border border-slate-800">
          <div className="text-xs text-slate-400">Active Live Traders</div>
          <div className="text-2xl font-black font-mono text-amber-400 mt-1">19 Traders</div>
          <div className="text-[10px] text-slate-400 mt-0.5">Generating continuous lot volume</div>
        </div>

        <div className="p-4 rounded-2xl bg-[#0e1420] border border-slate-800">
          <div className="text-xs text-slate-400">Total Earned to Date</div>
          <div className="text-2xl font-black font-mono text-emerald-400 mt-1">$3,420.50</div>
          <div className="text-[10px] text-slate-400 mt-0.5">Settled automatically</div>
        </div>

        <div className="p-4 rounded-2xl bg-[#0e1420] border border-slate-800">
          <div className="text-xs text-slate-400">Available for Payout</div>
          <div className="text-2xl font-black font-mono text-white mt-1">$480.00</div>
          <div className="text-[10px] text-amber-400 mt-0.5">Min threshold: $50</div>
        </div>
      </div>

      {/* Partner Tier Progress */}
      <div className="p-6 rounded-2xl bg-[#0e1420] border border-slate-800 shadow-xl space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-base font-bold text-white">Commission Tier Pathway</h3>
          <span className="text-xs text-amber-400 font-bold">22 more traders until Diamond (30%)</span>
        </div>

        <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden">
          <div className="bg-gradient-to-r from-amber-500 to-emerald-400 h-full w-[65%] rounded-full" />
        </div>

        <div className="grid grid-cols-4 gap-2 pt-2 text-center text-xs">
          <div className="p-2 rounded-xl bg-slate-900 border border-slate-800">
            <div className="text-slate-400">Bronze</div>
            <div className="font-bold text-white mt-0.5">15%</div>
            <div className="text-[10px] text-slate-500">1-5 Traders</div>
          </div>
          <div className="p-2 rounded-xl bg-slate-900 border border-slate-800">
            <div className="text-slate-400">Silver</div>
            <div className="font-bold text-white mt-0.5">20%</div>
            <div className="text-[10px] text-slate-500">6-15 Traders</div>
          </div>
          <div className="p-2 rounded-xl bg-amber-500/10 border border-amber-500/50">
            <div className="text-amber-400 font-bold">Gold (Current)</div>
            <div className="font-black text-amber-400 text-sm mt-0.5">25%</div>
            <div className="text-[10px] text-amber-400/80">16-40 Traders</div>
          </div>
          <div className="p-2 rounded-xl bg-slate-900 border border-slate-800">
            <div className="text-slate-400">Diamond VIP</div>
            <div className="font-bold text-white mt-0.5">30%</div>
            <div className="text-[10px] text-slate-500">40+ Traders</div>
          </div>
        </div>
      </div>

      {/* Payout Modal */}
      {isPayoutModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="relative w-full max-w-md bg-[#0e1420] border border-slate-800 rounded-3xl shadow-2xl p-6 text-slate-100 space-y-4">
            <h3 className="text-xl font-bold text-white">Withdraw Affiliate Earnings</h3>
            <p className="text-xs text-slate-400">
              Transfer your unlocked $480.00 commission to external crypto wallet or bank account.
            </p>

            <div className="grid grid-cols-2 gap-2">
              <button
                type="button"
                onClick={() => setPayoutMethod('USDT')}
                className={`p-2.5 rounded-xl border text-xs font-bold transition cursor-pointer ${
                  payoutMethod === 'USDT'
                    ? 'bg-amber-500/20 border-amber-500 text-amber-400'
                    : 'bg-slate-900 border-slate-800 text-slate-400'
                }`}
              >
                USDT (TRC20 / ERC20)
              </button>
              <button
                type="button"
                onClick={() => setPayoutMethod('BANK')}
                className={`p-2.5 rounded-xl border text-xs font-bold transition cursor-pointer ${
                  payoutMethod === 'BANK'
                    ? 'bg-amber-500/20 border-amber-500 text-amber-400'
                    : 'bg-slate-900 border-slate-800 text-slate-400'
                }`}
              >
                SWIFT / SEPA Wire
              </button>
            </div>

            <div>
              <label className="block text-xs font-semibold text-slate-300 mb-1">
                {payoutMethod === 'USDT' ? 'Receiving TRC20 Wallet Address' : 'IBAN / Swift Details'}
              </label>
              <input
                type="text"
                value={walletAddress}
                onChange={(e) => setWalletAddress(e.target.value)}
                className="w-full px-3.5 py-2 rounded-xl bg-slate-900 border border-slate-700 text-xs font-mono text-white"
              />
            </div>

            <div className="flex gap-2 pt-2">
              <button
                onClick={handlePayout}
                className="flex-1 py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 font-bold text-xs transition cursor-pointer"
              >
                Confirm Payout Request
              </button>
              <button
                onClick={() => setIsPayoutModalOpen(false)}
                className="px-4 py-2.5 rounded-xl bg-slate-800 text-slate-300 text-xs transition cursor-pointer"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
